import { Router, type IRouter } from "express";
import healthRouter from "./health";
import leadsRouter from "./leads";
import statsRouter from "./stats";
import analyticsRouter from "./analytics";
import documentsRouter from "./documents";
import publicStatusRouter from "./publicStatus";
import adminAuthRouter from "./adminAuth";
import adminUsersRouter from "./adminUsers";
import adminEmailRouter from "./adminEmail";
import adminLeadsRouter from "./adminLeads";
import adminCasesRouter from "./adminCases";
import adminEngagementsRouter from "./adminEngagements";
import adminMessagesRouter from "./adminMessages";
import adminAuditRouter from "./adminAudit";
import adminImportsRouter from "./adminImports";
import adminTimelineRouter from "./adminTimeline";
import adminCampaignsRouter from "./adminCampaigns";
import adminTemplatesRouter from "./adminTemplates";
import adminLifecycleRouter from "./adminLifecycle";
import adminUploadsRouter from "./adminUploads";
import unsubscribeRouter from "./unsubscribe";
import whatsappWebhookRouter from "./whatsappWebhook";
import billingWebhookRouter from "./billingWebhook";
import otpRouter from "./otp";
import { overstayIntakeRouter } from "./overstayIntake";
import { businessIntakeRouter } from "./businessIntake";
import { supportRouter } from "./support";

const router: IRouter = Router();

router.use(healthRouter);
router.use(leadsRouter);
router.use(statsRouter);
router.use(analyticsRouter);
router.use(documentsRouter);
router.use(publicStatusRouter);
router.use(adminAuthRouter);
router.use(adminUsersRouter);
router.use(adminEmailRouter);
router.use(adminLeadsRouter);
router.use(adminCasesRouter);
router.use(adminEngagementsRouter);
router.use(adminMessagesRouter);
router.use(adminAuditRouter);
router.use(adminImportsRouter);
router.use(adminTimelineRouter);
router.use(adminCampaignsRouter);
router.use(adminTemplatesRouter);
router.use(adminLifecycleRouter);
router.use(adminUploadsRouter);
router.use(unsubscribeRouter);
router.use(whatsappWebhookRouter);
router.use(billingWebhookRouter);
router.use(otpRouter);
router.use(overstayIntakeRouter);
router.use(businessIntakeRouter);
router.use(supportRouter);

export default router;
